Feature/#2
lassl/lassl.github.io pull request #31
Opened 2021-05-25 01:18 UTC by Ykmoon

2021-05-26 00:43 UTC, bzantium commented
- conflict 해소 필요
- 사진등록 부탁드립니다

2021-05-26 12:30 UTC, aisolab commented
> * conflict 해소 필요
> * 사진등록 부탁드립니다

@bzantium @Ykmoon conflict 해결된건가요?

2021-05-26 13:13 UTC, bzantium commented
아직 안된 것 같아요!

2021-05-28 09:44 UTC, soeque1 commented
@Ykmoon 확인 부탁드려요.

2021-05-28 09:49 UTC, soeque1 requested changes

2021-05-28 09:49 UTC, soeque1 commented on _config.yml
> +    display_name:youngki.moon
```suggestion
    display_name: youngki.moon
```

2021-05-28 09:49 UTC, soeque1 approved these changes

2021-05-30 13:26 UTC, bzantium approved these changes
LGTM

2021-06-05 03:39 UTC, merged